name: Build Site
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages-src

    - name: Install modules
      run: |
        npm i

    - name: Build
      run: |
        npm run build
      env:
        GITHUB_TOKEN: ${{ secrets.SECRET_THINGY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.SECRET_THINGY }}
        BRANCH: gh-pages
        FOLDER: public
